### ISSUE TITLE
Crossover Grading for Prisha by Harry

### ISSUE THREAD

**Issue by PrishaMaiti** [PrishaMaiti/DataStructures#1]
Files relevant to the challenges are DynamicMenu.java, DynamicMenuTest.java, SwapObjects.java, and Matrix.java: https://replit.com/@PrishaMaiti/DataStructures#Main.java

Scrum Team Repository (see Home and Web Project wiki pages): https://github.com/dsblack0/stickers_for_charity/wiki

Individual Github pages (if Code Explanations is not on there, it means Jekyll is still taking time to add the change): https://prishamaiti.github.io/DataStructures/
Code_Explanations.md file directly on GitHub just in case: https://github.com/PrishaMaiti/DataStructures/blob/main/Code_Explanations.md

**Comment by wiz124** [comment]
Score for Prisha: 2/3

Has running code albeit there is no menu for replit as per requested by challenge 1 (-.25)
Has notes for Tech talk 0 however code explanations aren't part of the page, the code explanations file is linked separately but has minimal  explanations (-.5)
code snippets part of the page has some frontend issues(-.25)
Has a solid plan for preparing for AP test.
