### ISSUE TITLE
Crossover Grading for Prisha by Rachel

### ISSUE THREAD

**Issue by PrishaMaiti** [PrishaMaiti/DataStructures#2]
Total Score: 3.3/5

Individual GitHub Page: https://prishamaiti.github.io/DataStructures/

Replit: https://replit.com/@PrishaMaiti/DataStructures#Main.java

**Comment by wrachel** [comment]
Everything is on Github Pages

Total individual checks: 7/12 
Individual Score: 2.4/4

Describe Linked Lists, Java Generic T: 
* 1/1 Describes linked lists and Java Generic T in notes on Github Pages

Queue Add and Delete
* 1/1 Has comments on the code with code snippets & review
*  0/1 has add function but is not running as intended
*  1/2 has individual implementation of delete, but running example is not as intended

Merge 2 Queues
* 0/3 did not complete this challenge (no comments or running code/implementation of challenge)

Build Stack and reverse Queue Order
* 2/2 Has the class definition
* 1/1 Has comments / review on github pages (as well as comments in code), and has a general purpose tester
* 1/1 Test case that reverses order works properly at run time
