### ISSUE TITLE
Crossover Grading for Prisha by Akhil

### ISSUE THREAD

**Issue by PrishaMaiti** [PrishaMaiti/DataStructures#4]
# Total Score: 4.75/5, Grader: Akhil Guntur
Replit: https://replit.com/@PrishaMaiti/DataStructures
GitHub Pages (Check Sorts on Nav): https://prishamaiti.github.io/DataStructures

**Comment by algolg** [comment]
## Overall Score: 4.75/5
### Graded By: Akhil Guntur


 - Sorts and Analysis -- Coding, Comments, and Documentation
    - [x] Build custom Bubble Sort, Selection Sort, Insertion Sort and Merge Sort. 
    - [x] Build a GitHub page that describes Sort implementations and the Big O complexity of these Sorts. 
    - [ ] Analysis 
        - Establish analytics including: time, comparisons and 
        - Average the results for each each Sort, run each at least 12 times and 5000 elements. You should throw out High and Low when doing 
        - Make your final/judgement on best sort considering Data Structure loading, Comparisons, Swaps, Big O complexity, and Time.

- [x] Individual GitHub pages, Replit, IntelliJ 
    - Organize files, directories and menus for all 
    - Make your GitHub pages fold into a personal 
    - Make sure all Code and Analytics runs on Replit and 
    - Ensure Individual GitHub Repository shows iteration on work (minimum of 10 commits on Java and 10 commits on Pages)

Your code runs well and your menu is easy to navigate. Upon running an algorithm, analytics, such as time, are displayed. The only problem with your code is that it does not average the collected times, which may make it harder to decide which algorithm is the most efficient. Other than that, your GitHub Pages looks complete and thorough. Great job!
